import Head from "next/head";
import Image from "next/image";
// import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import UpsRequest from "@/Components/UpsRequest";
import UpsRequestResult from "@/Components/UpsRequestResult";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Systeme UPS Selector</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/systeme.ico" />
      </Head>
      {/* <main className={styles.main}> */}
      <main>
        {/* <UpsRequest /> */}
        <UpsRequestResult />
      </main>
    </>
  );
}
